// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbLHWKtZyab2PwWvRkOq9NFFRE4oO7kqw',
    appId: '1:257263284665:web:4859568d1fa5691fe64668',
    messagingSenderId: '257263284665',
    projectId: 'aqua-watch-app',
    authDomain: 'aqua-watch-app.firebaseapp.com',
    storageBucket: 'aqua-watch-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC358DoK7qpFfhTBpI_PMLwtRDyTqeY10g',
    appId: '1:257263284665:android:344a44c3fae2e671e64668',
    messagingSenderId: '257263284665',
    projectId: 'aqua-watch-app',
    storageBucket: 'aqua-watch-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP49bRIndJLRRV6r4FOsC8Z1gCW46c5xI',
    appId: '1:257263284665:ios:3cb601e2d30130a4e64668',
    messagingSenderId: '257263284665',
    projectId: 'aqua-watch-app',
    storageBucket: 'aqua-watch-app.appspot.com',
    androidClientId: '257263284665-3t83speu3h37s8som7aa23tgbn3i72rk.apps.googleusercontent.com',
    iosClientId: '257263284665-ncckttahvra6cqkio8s6pcfifa0al0v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalMatrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP49bRIndJLRRV6r4FOsC8Z1gCW46c5xI',
    appId: '1:257263284665:ios:2b937bea911f9433e64668',
    messagingSenderId: '257263284665',
    projectId: 'aqua-watch-app',
    storageBucket: 'aqua-watch-app.appspot.com',
    androidClientId: '257263284665-3t83speu3h37s8som7aa23tgbn3i72rk.apps.googleusercontent.com',
    iosClientId: '257263284665-f8her89lvs2g3luo5a9bceho0jubtk13.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalMatrix.RunnerTests',
  );
}
