// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxaJA7Yf7Xc7VnQ9gESYFxWo9139zur0I',
    appId: '1:1048075781642:web:418d19d8ac01cad1e841f3',
    messagingSenderId: '1048075781642',
    projectId: 'legalmatrix-1f767',
    authDomain: 'legalmatrix-1f767.firebaseapp.com',
    storageBucket: 'legalmatrix-1f767.appspot.com',
    measurementId: 'G-TGQ9NYR72F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAamnn6YXqR3YcsolFRD8SywOO5_Wa323c',
    appId: '1:1048075781642:android:ffbf526a54e15dcbe841f3',
    messagingSenderId: '1048075781642',
    projectId: 'legalmatrix-1f767',
    storageBucket: 'legalmatrix-1f767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-y9LRabnRMdsbTkLQu9DCH5kzn1xgojY',
    appId: '1:1048075781642:ios:5137e462dea4d9d4e841f3',
    messagingSenderId: '1048075781642',
    projectId: 'legalmatrix-1f767',
    storageBucket: 'legalmatrix-1f767.appspot.com',
    iosClientId: '1048075781642-2v04fvqpme0l18ifeslt52c4su53qhbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalMatrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-y9LRabnRMdsbTkLQu9DCH5kzn1xgojY',
    appId: '1:1048075781642:ios:5137e462dea4d9d4e841f3',
    messagingSenderId: '1048075781642',
    projectId: 'legalmatrix-1f767',
    storageBucket: 'legalmatrix-1f767.appspot.com',
    iosClientId: '1048075781642-2v04fvqpme0l18ifeslt52c4su53qhbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalMatrix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxaJA7Yf7Xc7VnQ9gESYFxWo9139zur0I',
    appId: '1:1048075781642:web:f0920fae12b49204e841f3',
    messagingSenderId: '1048075781642',
    projectId: 'legalmatrix-1f767',
    authDomain: 'legalmatrix-1f767.firebaseapp.com',
    storageBucket: 'legalmatrix-1f767.appspot.com',
    measurementId: 'G-TTQM40P8QZ',
  );

}